#!/usr/bin/env bash

files=(
    ST7735.py
    accelerometer.py
    battle.py
    battle_menu.py
    boolpalette.py
    boot_screen.py
    buttons.py
    connect.py
    debug_menu.py
    debug_wireless.py
    device_io.py
    display.py
    early_board_init.py
    env.py
    factions.py
    flag_manager.py
    joystick.py
    layout.py
    logger.py
    main_controller.py
    menu.py
    microfont.py
    power.py
    settings.py
    ship_stats.py
    speaker.py
    upgrade.py
    view.py
    wireless.py
)

for file in "${files[@]}"; do
    cp "../../dev/${file}" .
done

echo "BUILD_TIME='$(date -u +%Y-%m-%dT%H:%M:%SZ)'" > build_info.py

MANIFEST_PREAMBLE=$(cat << 'EOF'
# Do not edit this file directly. It is auto-generated by sync_files.sh
# Run that script to update the list of files.
include("$(PORT_DIR)/boards/manifest.py")
EOF
)

{
    echo "$MANIFEST_PREAMBLE"
    for file in "${files[@]}"; do
        echo "module(\"${file}\")"
    done
    echo "module(\"build_info.py\")"
} > manifest.py
